apiVersion: v1
kind: Secret
metadata:
  name: framework-secrets
  namespace: federated-graph-framework
stringData:
  api-key: ${API_KEY}
  db-password: ${DB_PASSWORD}
  grafana-password: ${GRAFANA_PASSWORD}
type: Opaque
