apiVersion: v1
kind: Service
metadata:
  name: framework-api-service
  namespace: federated-graph-framework
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: framework-api
  type: ClusterIP
